### ISSUE TITLE
Footnotes enhacement

### ISSUE THREAD

**Issue by Semptic** [x4121/MUAS-LaTeX-Template#1]
Du könntest das footnote handling verbessern, indem du anstatt `\footnotemark` mit `\footnotetext{bla}` `\footnote[frame]{bla}` verwendest.

**Comment by x4121** [comment]
Danke, werde nach dem Hauptseminar noch mal recht viel ändern.

**Comment by x4121** [comment]
Hmm.. das scheint es auch nicht für alle Fälle zu fixen.
Solange man nicht in `#+LaTeX`-Blöcken schreibt, escaped org-mode bestimmte Zeichen im Text. Dadurch ist `#+LaTeX: \footnotetext[2]{\url{someUrl}}` möglich, `#+CAPTION: Url\footnote[frame]{\url{someUrl}}` aber nicht :confused:
